## Tuple(元祖)
tuple(元祖)可以視為不可改變的(list)。tuple跟list很像，但是不能新增或刪除或者更新tuple元素。  
tuple比起list的好處:
* 佔用空間少
* 可以當作dictionary(字典)的key
* 具名tuple當作物件替代
* 當作函式的引數

In [ ]:
a_list=['python','js','C#']
a_tuple=tuple(a_list)
b_tuple=('python','js','C#')
print(a_tuple)
print(b_tuple)

('python', 'js', 'C#')
('python', 'js', 'C#')


##Dictionary-dict(字典)
###dict為帶有鍵值(key)的串列
* 表示方法為{ }

In [ ]:
languaes={}
languages={'name':'python','version':'3.7'}
a_list=['pyhon','3.7']
print(a_list[0])
print(a_list[1])
a_dict={0:'python',1:'3.7'}
print(a_dict)
print(a_dict[0])#dict就是索引值可以改變list

pyhon
3.7
{0: 'python', 1: '3.7'}
python


In [ ]:
languages={'name':'python','version':'3.7'}
print(languages['name'])
print(languages)
print(languages.keys()) #返回一個字典裡所有的鍵
print(languages.values())#返回字典中的所有的值
print(languages.items()) #返回字典中所有(鍵,值)
print('name' in languages)

python
{'name': 'python', 'version': '3.7'}
dict_keys(['name', 'version'])
dict_values(['python', '3.7'])
dict_items([('name', 'python'), ('version', '3.7')])
True


In [ ]:
import random #亂數
dice=random.randint(1,6)
print('擲出骰子點數')
if dice==1:
  print('一點')
elif dice==2:
  print('二點')
elif dice==3:
  print('三點')
elif dice==4:
  print('四點')
elif dice==5:
  print('五點')
else:
  print('六點')

擲出骰子點數
六點


In [ ]:
import random
dice_points={1:'一點',2:'二點',3:'三點',4:'四點',5:'五點',6:'六點'}
dice=random.randint(1,6)
print('擲出骰子點數',dice_points[dice])

擲出骰子點數 五點


#numpy套件(numeric python)
##為甚麼需要numpy?
* numpy由c撰寫，速度快10~1000倍以上
* numpy儲存結果較正確，python數字儲存不正確
* numpy節省記憶體儲存時間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便

In [ ]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
#numpy套件的ndarray型態，提供element-wise的操作
import numpy as np
a=np.array([1,2,3,4,5])#np.array從串列變成numpy對話框
print(a*3)

[ 3  6  9 12 15]


array規定每一個元素都必須有相同的資料型態，它們在記憶體上的儲存位置會完全排在一起，因此array的存取速度會比list快非常多

In [ ]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape) #ndarray的形狀
print(a.dtype) #資料的型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(5,)
int64
1


In [ ]:
import numpy as np
z=np.zeros(6)
print(z)
print(np.empty((2,3,4))) #創建一個沒有任何具體值的ndarray數組
print(np.arange(10)) #創造numpy的陣列

[0. 0. 0. 0. 0. 0.]
[[[4.66272409e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5]) #0~4

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


# 2維資料取直

In [ ]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])
print(my_2d_array[:,1])
print(my_2d_array[1,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [ ]:
my_array=np.arange(0,10) 
print(my_array)
print(my_array.shape)
my_2d_array=my_array.reshape(2,5) #reshape改變陣列形狀 (numpy裡)
print(my_2d_array)
print((np.arange(0,100).reshape(10,10)))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# numpy的空值nan

In [ ]:
b=np.array([56,8,19,14,np.nan]) 
print(b)

[56.  8. 19. 14. nan]


#函式(數)
##傳統的寫法

In [ ]:
import math
radius=eval(input('請輸入圓的半徑:')) #把輸入的字串變成數學計算型態
print('圓的面積為:',radius*radius*math.pi)

請輸入圓的半徑:10
圓的面積為: 314.1592653589793


#面積計算涵式

In [1]:
import math
def circle_area(radius): #def定義函式
  area=radius*radius*math.pi
  return area
print(circle_area(10))

314.1592653589793


#Chap 6
##os套件:用來處理文件與目錄，與檔案相關操作

In [ ]:
import os
print(os.getcwd()) #顯示目前所在的工作目標

/content


In [ ]:
#顯示目錄下的檔案
os.listdir('.')

['.config', 'sample_data']

In [ ]:
#新增目錄
os.makedirs('test')
os.listdir('.')

['.config', 'test', 'sample_data']

In [ ]:
#移除目錄
os.rmdir('test')
os.listdir('.')

['.config', 'sample_data']

#檔案處理
os套件有自己的檔案處理命令，而比較常用的是python內建的open  
* w=可寫(預設建立檔案)若檔案存在則會清除舊檔案
* w+=可寫可讀(預設建立檔案)若檔案存在則會清除除舊檔案
* r=可讀
* r+=可讀可寫 但寫入資料指向開頭
* a=可寫不能讀 寫入資料指向尾端
* a+=可寫可讀 寫入資料指向尾端
* b=轉為2進為文件
* ab+=2進為文件的讀寫 寫入資料指向尾端

##新增檔案

In [ ]:
a=open('a.txt','w')#新增檔案
a.write('This is a test1 ')
a.write('This is a test2\n')
a.write('This is a test13\n')
a.close()#關閉檔案

##檢查檔案是否存在

In [ ]:
os.path.isfile('a.txt')

True

##讀取檔案

In [ ]:
a=open('a.txt','r')
print(a.readline())
print(a.readline())
print(a.readline()) #多餘的命令，檔案只有2行
a.close()

This is a test1 This is a test2

This is a test13




In [ ]:
a=open('a.txt','r')
print(a.readlines()) #一次讀取多行，與a.read()命令相同
a.close()

['This is a test1 This is a test2\n', 'This is a test13\n']


In [ ]:
#加上檔案是否存在的判斷
if os.path.isfile('a.txt'):
  a=open('a.txt','r')
  print(a.readlines())
  a.close()
else:
  print('檔案不存在')

['This is a test1 This is a test2\n', 'This is a test13\n']


##split

In [ ]:
if os.path.isfile('a.txt'):
  a=open('a.txt','r')
  for line in a: #全部行
    fields=line.split(' ') #以空白切割欄位
    print(fields)
  a.close()
else:
  print('檔案不存在')

['This', 'is', 'a', 'test1', 'This', 'is', 'a', 'test2\n']
['This', 'is', 'a', 'test13\n']


##附加檔案

In [ ]:
a=open('a.txt','a')
a.write('This is test 4\n')
a.close()

In [ ]:
a=open('a.txt','r')
print(a.readlines())
a.close()

['This is a test1 This is a test2\n', 'This is a test13\n', 'This is test 4\n']


#比較a與r+的不同
* a寫在檔案的結尾
* r+寫在檔案的開頭

In [ ]:
a=open('a.txt','r+')
a.write('This is a test 5\n')
a.close()

In [ ]:
a=open('a.txt','r+')
print(a.readlines())
a.close()

['This is a test 5\n', 'his is a test2\n', 'This is a test13\n', 'This is test 4\n']


##刪除檔案

In [ ]:
if os.path.isfile('a.txt'):
  os.remove('a.txt')
  print('刪除成功')
else:
  print('找不到檔案')
print(os.path.isfile('a.txt'))

刪除成功
False


##Chap7 錯誤處理
try:  
execept:  
else:  
finally:

In [2]:
a=10
b=20
if a<b:
  print(n)

NameError: ignored

In [ ]:
a=10
b=20
try:
  if a<b:
    print(n)
except:
  print('錯誤產生')

錯誤產生


##指定錯誤類別處理

In [ ]:
a=10
b=20
try:
  if a<b:
    print(n)
except NameError as e:
  print('錯誤產生,錯誤原因:',e)
except ZeroDivisionError:
  print('除以0錯誤')

錯誤產生,錯誤原因: name 'n' is not defined


##else
沒有錯誤產生會執行的部分

In [ ]:
a=1
b=20
try:
  if a<b: #改變比較條件，讓錯誤不發生
    print(n)
except:
  print('錯誤發生')
else:
  print('沒有錯誤發生時回執行的部分')

錯誤發生


In [ ]:
a=1
b=20
try:
  if a<b: #改變比較條件，讓錯誤不發生
    print(n)
except:
  print('錯誤發生')
else:
  print('沒有錯誤發生時回執行的部分')
finally:
  print('不管有沒有錯誤一定會執行的部分')

錯誤發生
不管有沒有錯誤一定會執行的部分
